apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wandb
  template:
    metadata:
      labels:
        app: wandb
    spec:
      containers:
      - name: wandb
        image: wandb/local:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: wandb-service
spec:
  selector:
    app: wandb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP