name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: cdquang/my-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # api-gateway
      - name: Build and push api-gateway image
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:api-gateway-latest
            ${{ env.DOCKER_REPO }}:api-gateway-${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

      # discovery-server
      - name: Build and push discovery-server image
        uses: docker/build-push-action@v6
        with:
          context: ./discovery-server
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:discovery-server-latest
            ${{ env.DOCKER_REPO }}:discovery-server-${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

      # flask (test)
      - name: Build and push flask-api image
        uses: docker/build-push-action@v6
        with:
          context: ./test
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:flask-api-latest
            ${{ env.DOCKER_REPO }}:flask-api-${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max


